"""empty message

Revision ID: 07b65cf1009f
Revises: 
Create Date: 2021-04-29 09:52:27.158117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b65cf1009f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('operationTime', sa.Float(), nullable=False),
    sa.Column('totalWorkingTime', sa.Float(), nullable=False),
    sa.Column('longestOpenedTime', sa.Float(), nullable=False),
    sa.Column('blinkCount', sa.Integer(), nullable=False),
    sa.Column('warningCount', sa.Integer(), nullable=False),
    sa.Column('alertCount', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_02',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('create_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_02')
    op.drop_table('usage_02')
    # ### end Alembic commands ###
