"""empty message

Revision ID: 11b32ef4cdcf
Revises: 
Create Date: 2021-05-20 09:50:11.618002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b32ef4cdcf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=150), nullable=False),
    sa.Column('subject_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('lecture_part', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('rate_posture', sa.Float(), nullable=False),
    sa.Column('rate_concentrate', sa.Float(), nullable=False),
    sa.Column('rate_angry', sa.Float(), nullable=False),
    sa.Column('rate_disgust', sa.Float(), nullable=False),
    sa.Column('rate_fear', sa.Float(), nullable=False),
    sa.Column('rate_happy', sa.Float(), nullable=False),
    sa.Column('rate_sad', sa.Float(), nullable=False),
    sa.Column('total_loop', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('div', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('study_log')
    op.drop_table('lecture')
    # ### end Alembic commands ###
