"""empty message

Revision ID: 7347a14682f6
Revises: 1d50edd7168b
Create Date: 2021-05-21 14:48:43.674304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7347a14682f6'
down_revision = '1d50edd7168b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
